@@include("parts/functions/da.js");
@@include("parts/functions/changeView.js");
@@include("parts/header-dropdown.js");
@@include("parts/burger-menu.js");
@@include("parts/theme-toggle.js");
@@include("parts/sliders.js");
@@include("parts/accordion.js");
@@include("parts/tabs.js");
@@include("parts/youtube-lazy.js");
